name:        hasklearn
version:     0.0.1.0
synopsis:    Initial project template
description: Please see README.md
category:    Machine Learning
author:      Sam Stites
maintainer:  sam@stites.io
github:      stites/hasklearn
license:     BSD3
copyright:   2017 Sam Stites

# FIXME: check to see if you can get clang and lld working
# ld-options:  -fuse-ld=lld
# ghc-options: "\"-pgmP clang\" \"-pgmc clang\" \"-pgma clang\" \"-pgml clang\"
#              -optl-fuse-ld=lld
#              -threaded
#              -rtsopts
#              -with-rtsopts=-N
#              -Wall"
#ld-options:  -fuse-ld=gold
#ghc-options: -optl-fuse-ld=gold
#             -threaded
#             -rtsopts
#             -with-rtsopts=-N
#             -Wall
#

default-extensions:
  - BangPatterns
  - LambdaCase
  - OverloadedStrings
  - ViewPatterns
  - NoImplicitPrelude
  - UndecidableInstances
  - MultiParamTypeClasses
  - FunctionalDependencies

dependencies:
  - base
  - numhask
  - hmatrix
  - statistics

library:
  source-dirs: src

tests:
#  doctest:
#    main: DocTest.hs
#    source-dirs: test
#    dependencies:
#      - hasklearn
#      - doctest

  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - QuickCheck
      - hasklearn
      - hspec
